M48
; DRILL file {KiCad (6.0.7-1)-1} date Sunday, December 11, 2022 at 09:40:08 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-11T21:40:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X1.1522Y-2.0866
X5.2459Y-1.8551
X5.2553Y-2.3327
T2
X1.2205Y-1.2992
X1.2205Y-2.874
X5.1575Y-1.2992
X5.1575Y-2.874
T0
M30
